### ISSUE TITLE
Comments on the initial version of the data model

### ISSUE THREAD

**Issue by kaiqu** [erasmus-without-paper/ewp-wp3-data-model#1]
In the previous version (distributed by email) we made a couple of changes that in retrospect seem less than optimal:
- Person Mobility was renamed to Nomination
- The relationships from LA Component to LOI were renamed from planned/recognized to sending/receiving

Both changes are rolled back in this version.

Other than that, the major changes in this version are as follows:
- The relationship between Person Mobility and LA is corrected from 1:1 to 1:N (possibly N revisions of the agreement)
- Added "recommended" relationship between LA Component and LOI
- LOS: Lang Code/Level (= language competence) is corrected to EQF Level
- LOI: The key is abstracted to a placeholder LOI Id for diagram clarity
  - The actual key is still a combination of Org Unit Id, LOS Code, Start Year/Term and End Year/Term
  - The relationships to Academic Term and LOS are still identifying the LOI, but the diagram tool now makes them look non-identifying (dashed)

There are also some minor changes such as:
- Renaming elements
- Making some elements repeated by an attribute (e.g. "lang" or "type")

**Comment by kaiqu** [comment]
General comments on the response schemas
- I assume the top level Organization Unit in the model (institution) is not meant to be represented in the department schema
- In my comments, I sometimes use common abbreviations ("los", "loi" etc.) in element names - whether the full names should be used in the format, is something I don't have strong opinions about
- Some of my comments (especially the ones that are repeated frequently) may be due to me not having followed the discussions very closely, or my lack of in-depth knowledge of XSD

**Comment by wrygiel** [comment]
> Both changes are rolled back in this version.

WP4 is proposing to rename "person mobility" to "mobility", at least in the XSDs. We have a separate thread for that here (with some arguments): https://github.com/erasmus-without-paper/ewp-wp3-technical-glossary/issues/1

> I assume the top level Organization Unit in the model (institution) is not meant to be represented in the department schema

The current name of the API (Departments API) does imply that. But if you decide that it should be represented there (e.g. a full tree-like structure), then this API can be renamed (e.g. to Organization Units API).

**Comment by wrygiel** [comment]
I will close this issue because there are no things "to do" here, I believe.

If you're looking for a place to summarize your changes, then I recommend creating a `CHANGELOG.md` file in your project (there are already some of those in other projects, like [here](https://github.com/erasmus-without-paper/ewp-specs-architecture/blob/stable-v1/CHANGELOG.md)).
