### ISSUE TITLE
Meaning of Cooperation Condition's EQF Level

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-wp3-data-model#11]
In @kaiqu's model each "Cooperation Condition" entity has an EQF Level.

What is the exact meaning of this field? This doesn't seem so obvious to me.

* From what I can deduce from [wiki](https://en.wikipedia.org/wiki/European_Qualifications_Framework), these levels work together with ISCED codes, and describe competences of the student in a specific field of study. Is this correct?
* When used in IIA context, is the student required to have this level *in advance* (`<required-eqf-level>`)?
* Or, perhaps, is he supposed to have this level *after* a successful mobility (`<target-eqf-level>`)?
* Is EQF Level field appropriate for staff mobilities too?

@erasmus-without-paper/all-members

**Comment by wrygiel** [comment]
Bonus question: Should we introduce EQF Levels in Courses API too (to describe "learning outcomes")?

**Comment by ghost** [comment]
@wrygiel EQF level refers to the study cycle: Short cycle (EQF-5), Bachelor (EQF-6), Master (EQF-7), Doctorate (EQF-8). If in an agreement is referred to MA, it is open to students that are enrolled in a masters programme at the moment of the exchange.

**Comment by wrygiel** [comment]
It seems that I completely misunderstood its meaning then, thank you.

So, this is supposed to be a modern replacement of the "study level" term we have previously used in [EMREX](https://github.com/emrex-eu/elmo-schemas/blob/69fe9e4b8021f5f118835c9f213f6d39af412c4f/schema.xsd#L1051) and the [Courses API](https://github.com/erasmus-without-paper/ewp-specs-api-courses/blob/v0.1.0/response.xsd#L326), right? If so, then I should probably replace the `<level>` element in the Courses API with `<eqf-level>`.

**Comment by vickalaser** [comment]
Hi,

Just to add that most EU countries should now have an alignment of their National Qualifications Framework to the EQF. This might be useful.

http://ec.europa.eu/ploteus/search/site?f[0]=im_field_entity_type%3A97

And here is an example comparison showing England & Northern Ireland, EQF, and Scotland.

https://ec.europa.eu/ploteus/en/compare?field_location_selection_tid%5B%5D=471&field_location_selection_tid%5B%5D=472


Anthony

**Comment by wrygiel** [comment]
I'm closing this. Here's a [link](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/v0.1.0/endpoints/get-response.xsd#L481) to the definition I have used in version 0.1.0 of IIAs API.
