### ISSUE TITLE
Role attr is still in contact/fact sheet

### ISSUE THREAD

**Issue by lennertVanSever** [erasmus-without-paper/ewp-wp3-data-model#13]
The attribute "Role" is still defined in the table "Contact/Fact sheet" while in the [XML there is no such attribute](https://github.com/erasmus-without-paper/ewp-specs-types-contact/blob/v1.1.0/schema.xsd). I already raised this [issue](https://github.com/erasmus-without-paper/ewp-specs-types-contact/issues/5) and it was shortly discussed in Porto but so far the XML hasn't been updated. So the Data Model should be updated.

**Comment by kaiqu** [comment]
I have uploaded a new README, which explains this (see under "Special entities").
