### ISSUE TITLE
Cooperation Condition table missing unbound EQF level

### ISSUE THREAD

**Issue by lennertVanSever** [erasmus-without-paper/ewp-wp3-data-model#14]
There are a couple of mismatches between the [Cooperation Condition table in the data-model](https://github.com/erasmus-without-paper/ewp-wp3-data-model/blob/master/data-model.pdf) and the specifications defined in the [API](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/v2.1.0/endpoints/get-response.xsd). 
<img width="503" alt="screen shot 2018-06-25 at 11 45 46" src="https://user-images.githubusercontent.com/23064517/41843257-5e5046cc-786d-11e8-948d-528e567c2683.png">
As you can see in the screenshot, the data-models defines that one cooperation condition can only contain: 
- One Receiving Academic Year ID
- One EQF level
- One Recommended language skill

While in the API documentation the following specifications are defined 
```
<xs:element name="receiving-academic-year-id" type="trm:AcademicYearId" minOccurs="1" maxOccurs="unbounded">
<xs:element name="eqf-level" type="ewp:EqfLevel" minOccurs="1" maxOccurs="unbounded">
<xs:element name="recommended-language-skill" minOccurs="0" maxOccurs="unbounded">
```
This means that the data-model should be updated to represent unbound occurrences of  EQF levels, Receiving Academic Year ID's and Recommended language skill

**Comment by kaiqu** [comment]
The star notation means that the attribute is repeated:
Receiving Academic Year ID* and Recommended Language Skill*
EQF Level should also have a star (in the next version).

**Comment by lennertVanSever** [comment]
You are right about the star, didn't noticed it. 
So yes in this case, the star is only missing next to the EQF level

**Comment by kaiqu** [comment]
I'm closing the issue, as all questions have been answered.
