### ISSUE TITLE
Drop Learning Agreement entity?

### ISSUE THREAD

**Issue by kaiqu** [erasmus-without-paper/ewp-wp3-data-model#4]
It seems to me the Learning Agreement entity is becoming superfluous:
- There is a Revision key attribute in LA
- We are introducing change tracking on the Mobility level via a Revision key attribute there as well
- The two entities would need separate Revision attributes (otherwise, a change in LA Components would necessitate a new Mobility copy with a new Revision)
- This seems messy
- As it is, there is only an optional Doc ID in LA
- Status = Accepted could by definition mean that there is a LA

I argue that Learning Agreement should be dropped as a separate entity - what do you think?

**Comment by wrygiel** [comment]
I believe so too. That's the reason why we have merged nominations and LAs into a single Mobility API.

Of course, some databases still can have separate tables for Nominations and Learning Agreements, but this would be a 0..1 relationship, so they can be merged in our base model.
