### ISSUE TITLE
Normalized/symmetrical modeling of Cooperation Conditions

### ISSUE THREAD

**Issue by kaiqu** [erasmus-without-paper/ewp-wp3-data-model#6]
Cooperation Condition is a tricky entity, and it's represented quite differently in the model and in the (coming version of the) format:

In the model:
- It's **normalized** - the numbers in each direction are in separate occurrences (for the same IIA Partners, Mobility Type and Start/End Date)
- It's **symmetrical** - as if it's stored by some neutral third party
  - It has a **direction** defined by a "from" Partner and a "to" Partner
- It represents how "things really are" (in some imagined, objective reality)

In the format:
- It's **denormalized** - the numbers in each direction are in the same occurrence (for the same IIA Partners, Mobility Type and Start/End Date)
- It's **asymmetrical** - as each partner stores its own version of the conditions (for both directions)
  - It has an "incoming" and an "outgoing" part, defined by the viewpoint:
    - If UW is local and UiO remote, one cooperation-condition element is represented as "mirror" occurrences of Cooperation Condition in the model:
      - Incoming = from UiO to UW
      - Outgoing = from UW to UiO
- It represents how data are stored at each HEI (both A and B store the numbers in both directions, and must agree on both)

In my opinion, the model should represent how "things really are". But that makes it in some cases harder to understand for developers who see reality from the viewpoint of a HEI.

Any opinions on this?

**Comment by wrygiel** [comment]
Perhaps we could replace "incoming HEI" and "outgoing HEI" with "HEI A" and "HEI B", where `A.id < B.id` in lexicographical order? This would make it symmetrical in the format.

We could also try to make the format normalized. This is just a representation.

I think some XML samples would help us make decisions here. It will be easier to grasp.

**Comment by kaiqu** [comment]
> Perhaps we could replace "incoming HEI" and "outgoing HEI" with "HEI A" and "HEI B", where A.id < B.id in lexicographical order? This would make it symmetrical in the format.

Sounds like a good idea. I will adjust the examples to that effect, unless someone has objections.

> We could also try to make the format normalized. This is just a representation.
> 
> I think some XML samples would help us make decisions here. It will be easier to grasp.

Ok, I will include both alternatives in the examples (with explanatory comments).

Anyway, I interpret your reply to agree with me that the model should represent "reality"...

**Comment by wrygiel** [comment]
> Anyway, I interpret your reply to agree with me that the model should represent "reality"...

Yes, but perhaps my reasoning is a little different:
- In case of symmetry: I think it would be clearer if - for any IIA - all its partners would be _able_ to serve _exactly_ the same XML via their IIAs API. (After all, they have signed _the same_ document.)
- In case of normalization: We cannot _really_ tell if the partner stores these in a symmetrical or asymmetrical format, because both are valid. So, either of them is okay here. So far, I don't have any preference.

**Comment by kaiqu** [comment]
> - In case of symmetry: I think it would be clearer if - for any IIA - all its partners would be _able_ to serve _exactly_ the same XML via their IIAs API. (After all, they have signed _the same_ document.)

I agree, and this seems to be solved by your suggestion about HEI A and HEI B.

> - In case of normalization: We cannot _really_ tell if the partner stores these in a symmetrical or asymmetrical format, because both are valid. So, either of them is okay here. So far, I don't have any preference.

True, we cannot tell. My concern was that a symmetrical format could be hard to understand by developers who see reality from the viewpoint of a HEI - and if it is normalized as well, it could be difficult if the local structure is denormalized. But I'm sure we have excellent developers who will grasp these things effortlessly :-)

**Comment by kaiqu** [comment]
In the current version of the format, I have chosen symmetrical/denormalized.

**Comment by thomj** [comment]
We prefer the version with `<partner instance="from">`. But this issue perhaps requires a special discussion?

**Comment by kaiqu** [comment]
> We prefer the version with 'partner instance="from"'. But this issue perhaps requires a special discussion?

In other words, alternative 2a (symmetrical Cooperation Conditions/Normalized). I'm happy that alt. 1 is ruled out, but why do you prefer 2a before 2b?

**Comment by kaiqu** [comment]
>> We prefer the version with 'partner instance="from"'. But this issue perhaps requires a special discussion?
> 
> In other words, alternative 2a (symmetrical Cooperation Conditions/Normalized). I'm happy that alt. 1 is ruled out, but why do you prefer 2a before 2b?

I leave this to @wrygiel.

**Comment by wrygiel** [comment]
I went with normalized symmetrical ([link](https://github.com/erasmus-without-paper/ewp-specs-api-iias/blob/v0.1.0/endpoints/get-response.xsd#L249)).
